### ISSUE TITLE
An internal error occurred during: "Updating Maven Project".

### ISSUE THREAD

**Issue by ahoehma** [qoomon/maven-git-versioning-extension#231]
I'm using 9.4.1 in my multi-module maven project.

If I run maven from cmd everything works fine.

If I run with eclipse (m2e) I got this error:

java.lang.NullPointerException
	at java.base/java.io.File.<init>(File.java:278)
	at me.qoomon.maven.gitversioning.GitVersioningModelProcessor.init(GitVersioningModelProcessor.java:137)
	at me.qoomon.maven.gitversioning.GitVersioningModelProcessor.processModel(GitVersioningModelProcessor.java:243)
	at me.qoomon.maven.gitversioning.GitVersioningModelProcessor.read(GitVersioningModelProcessor.java:120)
	at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:622)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:303)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:267)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:448)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:414)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:377)
	at org.eclipse.m2e.core.internal.IMavenToolbox.readMavenProjects(IMavenToolbox.java:117)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.lambda$11(ProjectRegistryManager.java:747)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:371)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.readMavenProjectFacades(ProjectRegistryManager.java:744)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:380)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:360)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:313)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration0(ProjectConfigurationManager.java:388)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.lambda$3(ProjectConfigurationManager.java:340)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:371)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:275)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:214)
	at org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1102)
	at org.eclipse.m2e.core.internal.project.ProjectConfigurationManager.updateProjectConfiguration(ProjectConfigurationManager.java:339)
	at org.eclipse.m2e.core.ui.internal.UpdateMavenProjectJob.runInWorkspace(UpdateMavenProjectJob.java:80)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

**Comment by ahoehma** [comment]
I found a workaround ...

in /cc/.mvn/maven-git-versioning-extension.xml

<disable>true</disable>

Then I'm able to refresh the project with m2e,

Hmm .. where is the issue ... here or in m2e? :D

**Comment by qoomon** [comment]
If it's working on command line it is probably a m2e issue. I'll try to reproduce the error, maybe I can find a workaround

**Comment by qoomon** [comment]
I can not reproduce your issue :-/

**Comment by ahoehma** [comment]
I'm using the latest snapshot of m2e ... maybe there is the problem.

Eclipse.org - m2e	M2E Maven Integration for Eclipse Core	2.2.0.20230103-1533	org.eclipse.m2e.feature

Maybe inside eclipse the current base-dir is different somehow?

I checked https://github.com/qoomon/maven-git-versioning-extension/blob/v9.4.1/src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java#L137

Seems that "mavenSession.getRequest().getBaseDirectory()" is empty in my case.

Maybe you can introduce an additional check in the extension ... seems "executionRootDirectory" is mandatory,

**Comment by qoomon** [comment]
I could skip git versioning incase of `mavenSession.getRequest().getBaseDirectory() == null`

**Comment by qoomon** [comment]
feel free to try version `9.4.2`
