### ISSUE TITLE
Maven 4.0.0-x compatibility

### ISSUE THREAD

**Issue by sureshg** [qoomon/maven-git-versioning-extension#334]
Getting this error when running on maven [4.0.0-Beta4](https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/4.0.0-beta-4/apache-maven-4.0.0-beta-4-bin.zip)

```
Exception in thread "main" java.lang.AbstractMethodError: Receiver class me.qoomon.maven.gitversioning.GitVersioningModelProcessor does not define or inherit an implementation of the resolved method 'abstract java.nio.file.Path locateExistingPom(java.nio.file.Path)' of interface org.apache.maven.model.locator.ModelLocator.
        at org.apache.maven.model.locator.ModelLocator.locateExistingPom(ModelLocator.java:64)
        at org.apache.maven.cli.MavenCli.determinePom(MavenCli.java:1435)
        at org.apache.maven.cli.MavenCli.populateRequest(MavenCli.java:1323)
        at org.apache.maven.cli.MavenCli.populateRequest(MavenCli.java:1297)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:208)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:573)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:255)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:201)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:361)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:314)
`
```

**Comment by qoomon** [comment]
Although I fixed this issue, the extension is not loaded anymore. I assume maven 4.0.0 has changed how core extensions ar working or how DI is done.

**Comment by theit** [comment]
A couple of days ago I wanted to give Maven 4.0.0-rc-1 a try on a multi-module project and had to find out that the extension doesn't work anymore, neither with rc-1 nor with the recently released rc-2. I asked on the mailing list, and got the following respons from @cstamas:

> In short, the extension is not compatible with Maven4 due this "trick":
https://github.com/qoomon/maven-git-versioning-extension/blob/master/src/main/java/me/qoomon/maven/gitversioning/GitVersioningModelProcessor.java
> 
> To properly support Maven4, this extension would need to be "enabled"
for Maven4, very similar like Nisse was recently:
https://github.com/maveniverse/nisse/commit/a24a8e90e39d50ae479e5e3e92b6ad643849e147#diff-eaf45ebe6b14a5aaad3400949a1a9a22c8b09f49acc9683dbb28eaf21bf93895
> 
> In short: Maven4 PropertyContributor SPI should be used instead.

See https://lists.apache.org/thread/z3sy75xvwrfcwpnnh9gs4f2x0qv7dgrs

**Comment by qoomon** [comment]
@theit thanks for details, I'll see if I can adjust this extension accordingly.

**Comment by qoomon** [comment]
So if I got this right I need to implement following interface instead of `ModelProcessor`
[`ModelParser`](https://github.com/apache/maven/blob/master/api/maven-api-spi/src/main/java/org/apache/maven/api/spi/ModelParser.java)

**Comment by hamnis** [comment]
It does not fail any more, but the version is not replaced.
Maven 4 allows any properties to be used in the `version` element in the build, so I expect if the extension changes to known property in the build, then it would work
